/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Prediction {
  'id' : bigint,
  'homeTeam' : string,
  'note' : string,
  'homeScore' : bigint,
  'timestamp' : Time,
  'awayTeam' : string,
  'awayScore' : bigint,
}
export interface Team {
  'goalDiff' : bigint,
  'played' : bigint,
  'name' : string,
  'wins' : bigint,
  'goalsFor' : bigint,
  'losses' : bigint,
  'goalsAgainst' : bigint,
  'position' : bigint,
  'draws' : bigint,
  'points' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'deletePrediction' : ActorMethod<[bigint], boolean>,
  'getPredictions' : ActorMethod<[], Array<Prediction>>,
  'getTeams' : ActorMethod<[], Array<Team>>,
  'savePrediction' : ActorMethod<
    [string, string, bigint, bigint, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];