/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Prediction = IDL.Record({
  'id' : IDL.Nat,
  'homeTeam' : IDL.Text,
  'note' : IDL.Text,
  'homeScore' : IDL.Nat,
  'timestamp' : Time,
  'awayTeam' : IDL.Text,
  'awayScore' : IDL.Nat,
});
export const Team = IDL.Record({
  'goalDiff' : IDL.Int,
  'played' : IDL.Nat,
  'name' : IDL.Text,
  'wins' : IDL.Nat,
  'goalsFor' : IDL.Nat,
  'losses' : IDL.Nat,
  'goalsAgainst' : IDL.Nat,
  'position' : IDL.Nat,
  'draws' : IDL.Nat,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deletePrediction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getPredictions' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
  'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'savePrediction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Prediction = IDL.Record({
    'id' : IDL.Nat,
    'homeTeam' : IDL.Text,
    'note' : IDL.Text,
    'homeScore' : IDL.Nat,
    'timestamp' : Time,
    'awayTeam' : IDL.Text,
    'awayScore' : IDL.Nat,
  });
  const Team = IDL.Record({
    'goalDiff' : IDL.Int,
    'played' : IDL.Nat,
    'name' : IDL.Text,
    'wins' : IDL.Nat,
    'goalsFor' : IDL.Nat,
    'losses' : IDL.Nat,
    'goalsAgainst' : IDL.Nat,
    'position' : IDL.Nat,
    'draws' : IDL.Nat,
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    'deletePrediction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getPredictions' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
    'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'savePrediction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };